### ISSUE TITLE
Handshake failure

### ISSUE THREAD

**Issue by satur9nine** [clover/pskfactories#3]
I noticed that some older Android devices are struggling to accept connections via NanoHTTPD. The following error appeared in logs.

```
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: raiseAlertFatal(BcPskSSLServerSocketFactory.java:56)[NanoHttpd Main Listener]: Alert fatal Failed to read record
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: org.bouncycastle.tls.TlsFatalAlert: bad_record_mac(20)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.crypto.impl.bc.BcChaCha20Poly1305.doFinal(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.decodeCiphertext(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.RecordStream.decodeAndVerify(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at org.bouncycastle.tls.TlsServerProtocol.accept(Unknown Source)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at com.clover.pskfactories.BcPskSSLServerSocketFactory$2.accept(BcPskSSLServerSocketFactory.java:225)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1769)
10-18 15:18:06.246 22135 22287 W BcPskTlsServerProtocol: 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by satur9nine** [comment]
I wasn't able to fully root cause this issue. Annoyingly BouncyCastle JARs distributed via Maven are built without debugging metadata making it impossible to interactively debug the code inside BouncyCastle--this is also why the line numbers are missing in the stack trace and it says "Unknown Source".

I tried building BouncyCastle locally and including the debugging symbols but the error magically doesn't occur when I do that.

The best solution I could come up with use to remove the CHACHA20 cipher suites from the list of supported suites:

    CipherSuite.TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256
    CipherSuite.TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256

This leaves the following cipher suite as the only supported suite, which is still fully secure and widely supported:

    CipherSuite.TLS_DHE_PSK_WITH_AES_128_GCM_SHA256

After this change older Android devices stopped having handshake failures. You may make this adjustment yourself to the top of the BcPskTlsParams class if you experience similar issues.
